### ISSUE TITLE
Data Pipeline e2e for SentryFlow

### ISSUE THREAD

**Issue by nandhued** [5GSEC/SentryFlow#18] opened 2024-09-19 03:41 UTC
Part of https://github.com/5GSEC/SentryFlow/issues/26

**Comment by nandhued** [comment] 2024-10-14 03:54
Blocked due to: https://github.com/accuknox/dev2/pull/216

**Comment by anurag-rajawat** [comment] 2024-10-27 13:42
Duplicate of https://github.com/5GSEC/SentryFlow/issues/26

**Closed by anurag-rajawat** 2024-10-27 13:42 UTC
