### ISSUE TITLE
Discovery and cataloging

### ISSUE THREAD

**Issue by nandhued** [5GSEC/SentryFlow#7] opened 2024-03-18 05:01 UTC
Based on the access logs provided from Istio, we need to catalog the API requests

- how to summarize the Access logs (URLs) to generate the SOB -> Summary Engine will do this.
- how will the UI look like

**Comment by anurag-rajawat** [comment] 2024-10-27 13:39
Duplicate of https://github.com/5GSEC/SentryFlow/issues/26

**Closed by anurag-rajawat** 2024-10-27 13:39 UTC
